-- ============================================================================
-- Team Compass / Family App / English Learning
-- Supabase schema (Postgres)
--
-- Conventions:
--   - All table and column names are English (snake_case)
--   - All comments are bilingual (EN first, JA after)
--   - Timestamps use timestamptz, default now() at UTC
--   - PKs are uuid generated by gen_random_uuid()
--   - No PII is hard-coded; all real data is inserted at runtime via the app
--
-- Apply order: this file (01_schema.sql) -> 02_rls.sql -> 03_seed.sql
-- ============================================================================

-- Required extension for gen_random_uuid()
create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- families: one row per household using the app
--           家族単位。家族コードでログインする
-- ----------------------------------------------------------------------------
create table if not exists families (
  id           uuid primary key default gen_random_uuid(),
  family_code  text not null unique,             -- short shareable code (e.g. "HAYASHI-2026")
  display_name text not null,                    -- e.g. "Hayashi Family"
  created_at   timestamptz not null default now()
);
comment on table families is 'One row per household. Login is by family_code.';

-- ----------------------------------------------------------------------------
-- family_members: people in a family. Roles drive UI behaviour.
--                 家族メンバー。役割で画面の見え方が変わる
-- ----------------------------------------------------------------------------
create table if not exists family_members (
  id            uuid primary key default gen_random_uuid(),
  family_id     uuid not null references families(id) on delete cascade,
  role          text not null check (role in
                  ('father','mother','son','daughter','grandparent','other')),
  display_name  text not null,                   -- nickname shown in UI; not necessarily real name
  emoji         text not null default '👤',
  color         text not null default '#888888', -- hex color for UI accent
  english_level int  not null default 1 check (english_level between 1 and 5),
                                                 -- 1: Eiken 5/4 (super basic)
                                                 -- 2: Eiken 4/3 (middle school basic)
                                                 -- 3: Eiken 3/Pre-2 (middle school complete)
                                                 -- 4: Eiken 2 (high school standard)
                                                 -- 5: Eiken Pre-1 (advanced)
  is_learner    boolean not null default true,   -- false = viewer-only (e.g. mother)
  pin_hash      text,                            -- optional 4-digit PIN, hashed
  birthdate     date,                            -- optional, only stored if user enters it
  sort_order    int not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists idx_family_members_family on family_members(family_id);
comment on table family_members is 'People in a family. role + english_level drive content selection.';

-- ----------------------------------------------------------------------------
-- vocabulary_items: shared word bank (all families read the same items)
--                   語彙バンク。全家族で共有する読み取り専用マスタ
-- ----------------------------------------------------------------------------
create table if not exists vocabulary_items (
  id            uuid primary key default gen_random_uuid(),
  word_en       text not null,
  meaning_ja    text not null,
  pos           text,                            -- part of speech: noun, verb, adj, adv, ...
  level         int  not null check (level between 1 and 5),
  category      text,                            -- 'daily','school','soccer','food','grammar', ...
  example_en    text,
  example_ja    text,
  audio_url     text,                            -- pre-recorded native MP3 URL (Supabase Storage)
  ipa           text,                            -- IPA pronunciation, optional
  notes         text,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);
create index if not exists idx_vocab_level     on vocabulary_items(level);
create index if not exists idx_vocab_category  on vocabulary_items(category);
create unique index if not exists uq_vocab_word on vocabulary_items(lower(word_en));
comment on table vocabulary_items is 'Shared vocabulary master. Read-only from app; populated by admin/seed.';

-- ----------------------------------------------------------------------------
-- vocab_progress: per-member SRS state for each vocabulary item
--                 メンバーごとの間隔反復(SRS)状態
-- ----------------------------------------------------------------------------
create table if not exists vocab_progress (
  id                  uuid primary key default gen_random_uuid(),
  member_id           uuid not null references family_members(id) on delete cascade,
  vocab_id            uuid not null references vocabulary_items(id) on delete cascade,
  status              text not null default 'new'
                        check (status in ('new','learning','review','mastered')),
  ease_factor         numeric(4,2) not null default 2.50,  -- Anki-style ease factor
  interval_days       int  not null default 0,
  consecutive_correct int  not null default 0,
  total_attempts      int  not null default 0,
  total_correct       int  not null default 0,
  last_reviewed_at    timestamptz,
  next_review_at      timestamptz,
  updated_at          timestamptz not null default now(),
  unique (member_id, vocab_id)
);
create index if not exists idx_progress_due on vocab_progress(member_id, next_review_at);
comment on table vocab_progress is 'SRS state per (member, vocab). next_review_at drives "today''s 20".';

-- ----------------------------------------------------------------------------
-- learning_sessions: a practice session (today's 20, mistake review, test, ...)
--                    1セッション分の学習記録
-- ----------------------------------------------------------------------------
create table if not exists learning_sessions (
  id              uuid primary key default gen_random_uuid(),
  member_id       uuid not null references family_members(id) on delete cascade,
  session_type    text not null check (session_type in
                    ('daily20','mistake_review','word_card','sprint_composition',
                     'phrase_scene','test')),
  started_at      timestamptz not null default now(),
  ended_at        timestamptz,
  total_questions int not null default 0,
  correct_count   int not null default 0,
  duration_ms     int
);
create index if not exists idx_sessions_member_started
  on learning_sessions(member_id, started_at desc);

-- ----------------------------------------------------------------------------
-- answer_logs: every answered question (for "mistake review" and analytics)
--              問題1問ごとの解答ログ
-- ----------------------------------------------------------------------------
create table if not exists answer_logs (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references learning_sessions(id) on delete cascade,
  member_id     uuid not null references family_members(id) on delete cascade,
  vocab_id      uuid references vocabulary_items(id) on delete set null,
  prompt        text,                            -- what the user saw (e.g. "水")
  expected      text,                            -- expected answer (e.g. "water")
  response      text,                            -- what the user typed/picked
  is_correct    boolean not null,
  response_ms   int,
  created_at    timestamptz not null default now()
);
create index if not exists idx_answers_member_wrong
  on answer_logs(member_id, is_correct, created_at desc)
  where is_correct = false;
comment on index idx_answers_member_wrong is 'Fast lookup of recent mistakes per member.';

-- ----------------------------------------------------------------------------
-- daily_stats: daily roll-up per member (for family ranking + streaks)
--              日次集計。家族ランキング・連続日数の元データ
-- ----------------------------------------------------------------------------
create table if not exists daily_stats (
  id              uuid primary key default gen_random_uuid(),
  member_id       uuid not null references family_members(id) on delete cascade,
  stat_date       date not null,                 -- local date in family timezone
  total_attempts  int not null default 0,
  total_correct   int not null default 0,
  accuracy_pct    numeric(5,2) not null default 0.00,
  minutes_studied int not null default 0,
  streak_days     int not null default 0,
  unique (member_id, stat_date)
);
create index if not exists idx_daily_stats_date on daily_stats(stat_date desc);

-- ----------------------------------------------------------------------------
-- support_messages: cheering / reward messages from one member to another
--                   応援メッセージ。母→子の「ご褒美ボックス」用途
-- ----------------------------------------------------------------------------
create table if not exists support_messages (
  id                uuid primary key default gen_random_uuid(),
  family_id         uuid not null references families(id) on delete cascade,
  from_member_id    uuid not null references family_members(id) on delete cascade,
  to_member_id      uuid references family_members(id) on delete cascade,
                                                  -- null = to whole family
  message           text,
  image_url         text,                         -- Supabase Storage URL
  unlock_condition  text not null default 'open_now'
                      check (unlock_condition in
                        ('open_now','session_complete','streak_3','streak_7','custom')),
  unlock_payload    jsonb,                        -- e.g. {"required_streak": 5}
  unlocked_at       timestamptz,
  reaction_emoji    text,                         -- recipient's reaction
  created_at        timestamptz not null default now()
);
create index if not exists idx_support_to_member on support_messages(to_member_id);
create index if not exists idx_support_family    on support_messages(family_id);

-- ----------------------------------------------------------------------------
-- activity_feed: the family timeline ("〇〇 が 30問正解")
--                家族タイムライン。学習活動が自動で投稿される
-- ----------------------------------------------------------------------------
create table if not exists activity_feed (
  id          uuid primary key default gen_random_uuid(),
  family_id   uuid not null references families(id) on delete cascade,
  member_id   uuid not null references family_members(id) on delete cascade,
  kind        text not null check (kind in
                ('session_done','streak_milestone','level_up','new_word_mastered',
                 'reward_unlocked','custom')),
  payload     jsonb,                              -- flexible details per kind
  created_at  timestamptz not null default now()
);
create index if not exists idx_feed_family_time
  on activity_feed(family_id, created_at desc);
