-- ============================================================================
-- Seed: 30 sample vocabulary items spanning L1..L5
--
-- This is the smallest viable set to drive a working "today's 20" demo.
-- Categories used: daily, school, soccer, general.
-- audio_url is left null for now; we'll backfill once we record native MP3s
-- and upload them to Supabase Storage at bucket "vocab-audio".
--
-- Idempotent: re-running this file will not create duplicates because of
-- the unique index on lower(word_en).
-- ============================================================================

insert into vocabulary_items (word_en, meaning_ja, pos, level, category, example_en, example_ja) values
  -- ----- L1 (super basic, Eiken 5/4) -----
  ('water',    '水',                 'noun', 1, 'daily',  'I drink water every day.',          '私は毎日水を飲みます。'),
  ('food',     '食べ物',             'noun', 1, 'daily',  'I like Japanese food.',             '私は日本食が好きです。'),
  ('friend',   '友達',               'noun', 1, 'daily',  'She is my best friend.',            '彼女は私の親友です。'),
  ('school',   '学校',               'noun', 1, 'school', 'I go to school by bus.',            '私はバスで学校へ行きます。'),
  ('happy',    '幸せな',             'adj',  1, 'daily',  'I am happy today.',                 '私は今日幸せです。'),
  ('run',      '走る',               'verb', 1, 'daily',  'I run every morning.',              '私は毎朝走ります。'),
  ('ball',     'ボール',             'noun', 1, 'soccer', 'Pass the ball, please!',            'ボールをパスして！'),
  ('mother',   '母',                 'noun', 1, 'family', 'My mother is very kind.',           '私の母はとても優しいです。'),
  ('father',   '父',                 'noun', 1, 'family', 'My father works at a restaurant.',  '私の父はレストランで働いています。'),
  ('brother',  '兄弟',               'noun', 1, 'family', 'I have one brother.',               '私には兄弟が一人います。'),
  ('sister',   '姉妹',               'noun', 1, 'family', 'She is my older sister.',           '彼女は私の姉です。'),
  ('dog',      '犬',                 'noun', 1, 'daily',  'We have a small dog.',              '私たちは小さな犬を飼っています。'),
  ('cat',      '猫',                 'noun', 1, 'daily',  'The cat is on the chair.',          '猫がいすの上にいます。'),
  ('eat',      '食べる',             'verb', 1, 'daily',  'I eat breakfast at seven.',         '私は7時に朝食を食べます。'),
  ('drink',    '飲む',               'verb', 1, 'daily',  'Drink some water, please.',         '水を少し飲んでください。'),
  ('sleep',   '寝る',                'verb', 1, 'daily',  'I sleep eight hours a night.',      '私は一晩に8時間寝ます。'),
  ('read',    '読む',                'verb', 1, 'school', 'I read books every day.',           '私は毎日本を読みます。'),
  ('write',   '書く',                'verb', 1, 'school', 'Please write your name here.',      'ここに名前を書いてください。'),
  ('like',    '好きである',          'verb', 1, 'daily',  'I like cats very much.',            '私は猫がとても好きです。'),
  ('book',    '本',                  'noun', 1, 'school', 'This book is interesting.',         'この本は面白いです。'),
  ('pen',     'ペン',                'noun', 1, 'school', 'Can I borrow your pen?',            'あなたのペンを借りてもいいですか？'),
  ('house',   '家',                  'noun', 1, 'daily',  'Their house is very big.',          '彼らの家はとても大きいです。'),
  ('big',     '大きい',              'adj',  1, 'general','That is a big tree.',               'あれは大きな木です。'),
  ('small',   '小さい',              'adj',  1, 'general','She has a small bag.',              '彼女は小さなかばんを持っています。'),
  ('good',    'よい',                'adj',  1, 'general','Good morning, everyone!',           'みなさん、おはようございます！'),

  -- ----- L2 (middle school basic, Eiken 4/3) -----
  ('play',     '(スポーツを)する・遊ぶ', 'verb', 2, 'soccer',  'I play soccer with my friends.',     '私は友達とサッカーをします。'),
  ('enjoy',    '楽しむ',             'verb', 2, 'daily',   'I enjoy reading books.',             '私は読書を楽しみます。'),
  ('practice', '練習する',           'verb', 2, 'soccer',  'We practice every day after school.','私たちは放課後毎日練習します。'),
  ('become',   '〜になる',            'verb', 2, 'general', 'I want to become a teacher.',        '私は先生になりたいです。'),
  ('important','重要な',             'adj',  2, 'general', 'It is important to study every day.','毎日勉強することは大切です。'),
  ('usually',  'たいてい',           'adv',  2, 'general', 'I usually wake up at seven.',        '私はたいてい7時に起きます。'),
  ('different','違った',             'adj',  2, 'general', 'We have different opinions.',        '私たちは違う意見を持っています。'),
  ('enough',   '十分な',             'adj',  2, 'general', 'I have enough money for lunch.',     'お昼ご飯のための十分なお金があります。'),
  ('study',    '勉強する',           'verb', 2, 'school',  'I study English every day.',         '私は毎日英語を勉強します。'),
  ('teacher',  '先生',               'noun', 2, 'school',  'My English teacher is from Canada.', '私の英語の先生はカナダ出身です。'),
  ('student',  '生徒',               'noun', 2, 'school',  'She is a high school student.',      '彼女は高校生です。'),
  ('homework', '宿題',               'noun', 2, 'school',  'I have a lot of homework today.',    '今日は宿題がたくさんあります。'),
  ('learn',    '学ぶ',               'verb', 2, 'school',  'I want to learn how to cook.',       '料理の仕方を学びたいです。'),
  ('understand','理解する',          'verb', 2, 'school',  'Do you understand this question?',   'この質問が分かりますか？'),
  ('remember', '覚えている',         'verb', 2, 'general', 'I remember her name.',               '彼女の名前を覚えています。'),
  ('forget',   '忘れる',             'verb', 2, 'general', 'Don''t forget your umbrella.',       '傘を忘れないでね。'),
  ('start',    '始める',             'verb', 2, 'daily',   'Let''s start the meeting.',          '会議を始めましょう。'),
  ('finish',   '終える',             'verb', 2, 'daily',   'I finished my report.',              'レポートを終わらせました。'),
  ('easy',     '簡単な',             'adj',  2, 'general', 'This question is easy.',             'この問題は簡単です。'),
  ('difficult','難しい',             'adj',  2, 'general', 'Math is difficult for me.',          '数学は私には難しいです。'),
  ('busy',     '忙しい',             'adj',  2, 'daily',   'She is very busy this week.',        '彼女は今週とても忙しいです。'),
  ('tired',    '疲れた',             'adj',  2, 'daily',   'I''m tired after the practice.',     '練習の後、疲れています。'),
  ('goal',     '目標・ゴール',       'noun', 2, 'soccer',  'He scored a goal in the game.',      '彼は試合でゴールを決めました。'),
  ('coach',    'コーチ',             'noun', 2, 'soccer',  'Our coach is very strict.',          '私たちのコーチはとても厳しいです。'),
  ('country',  '国',                 'noun', 2, 'daily',   'Japan is a beautiful country.',      '日本は美しい国です。'),
  -- L2 (continued) — school
  ('class',    '授業',               'noun', 2, 'school',  'We have English class at ten.',      '私たちは10時に英語の授業があります。'),
  ('library',  '図書館',             'noun', 2, 'school',  'She studies at the library.',        '彼女は図書館で勉強します。'),
  ('science',  '理科・科学',         'noun', 2, 'school',  'Science is my favorite subject.',    '理科は私の好きな科目です。'),
  ('math',     '数学',               'noun', 2, 'school',  'I have a math test tomorrow.',       '明日数学のテストがあります。'),
  ('history',  '歴史',               'noun', 2, 'school',  'I love Japanese history.',           '私は日本の歴史が大好きです。'),
  ('music',    '音楽',               'noun', 2, 'school',  'He listens to music every day.',     '彼は毎日音楽を聞きます。'),
  ('art',      '美術',               'noun', 2, 'school',  'Her art is amazing.',                '彼女のアートは素晴らしいです。'),
  ('test',     'テスト',             'noun', 2, 'school',  'I passed the test.',                 '私はテストに合格しました。'),
  ('answer',   '答え',               'noun', 2, 'school',  'What is the answer to this question?', 'この質問の答えは何ですか？'),
  ('question', '質問',               'noun', 2, 'school',  'I have a question for you.',         'あなたに質問があります。'),
  ('classroom','教室',               'noun', 2, 'school',  'The classroom is very quiet.',       '教室はとても静かです。'),
  ('lesson',   'レッスン・授業',     'noun', 2, 'school',  'Today''s lesson was interesting.',   '今日の授業は面白かったです。'),
  ('classmate','クラスメイト',       'noun', 2, 'school',  'He is my best classmate.',           '彼は私のいちばんのクラスメイトです。'),
  -- L2 (continued) — daily / travel
  ('airport',  '空港',               'noun', 2, 'daily',   'Pick me up at the airport, please.', '空港まで迎えに来てください。'),
  ('train',    '電車',               'noun', 2, 'daily',   'I take the train to school.',        '私は電車で学校へ行きます。'),
  ('station',  '駅',                 'noun', 2, 'daily',   'The station is near my house.',      '駅は私の家の近くです。'),
  ('bus',      'バス',               'noun', 2, 'daily',   'The bus comes every ten minutes.',   'バスは10分おきに来ます。'),
  ('ticket',   '切符・チケット',     'noun', 2, 'daily',   'I bought two tickets for the game.', '試合のチケットを2枚買いました。'),
  ('hotel',    'ホテル',             'noun', 2, 'daily',   'We stayed at a small hotel.',        '私たちは小さなホテルに泊まりました。'),
  ('restaurant','レストラン',        'noun', 2, 'daily',   'This restaurant is famous for sushi.', 'このレストランは寿司で有名です。'),
  ('menu',     'メニュー',           'noun', 2, 'daily',   'Can I see the menu, please?',        'メニューを見せてもらえますか？'),
  ('supermarket','スーパー',         'noun', 2, 'daily',   'I went to the supermarket after school.', '放課後スーパーへ行きました。'),
  ('weather',  '天気',               'noun', 2, 'daily',   'How is the weather today?',          '今日の天気はどうですか？'),
  ('season',   '季節',               'noun', 2, 'daily',   'Spring is my favorite season.',      '春は私の好きな季節です。'),
  ('weekend',  '週末',               'noun', 2, 'daily',   'Have a great weekend!',              'よい週末を！'),
  -- L2 (continued) — food & drink
  ('breakfast','朝食',               'noun', 2, 'daily',   'I always eat breakfast.',            '私はいつも朝食を食べます。'),
  ('dinner',   '夕食',               'noun', 2, 'daily',   'Dinner is ready!',                   '夕食ができました！'),
  ('fruit',    '果物',               'noun', 2, 'daily',   'I like fresh fruit.',                '私は新鮮な果物が好きです。'),
  ('vegetable','野菜',               'noun', 2, 'daily',   'Eat your vegetables.',               '野菜を食べなさい。'),
  ('meat',     '肉',                 'noun', 2, 'daily',   'He doesn''t eat meat.',              '彼は肉を食べません。'),
  ('rice',     'ご飯・米',           'noun', 2, 'daily',   'Japanese people eat rice every day.', '日本人は毎日ご飯を食べます。'),
  ('bread',    'パン',               'noun', 2, 'daily',   'I had bread for breakfast.',         '朝食にパンを食べました。'),
  ('juice',    'ジュース',           'noun', 2, 'daily',   'Would you like some juice?',         'ジュースはいかがですか？'),
  -- L2 (continued) — soccer
  ('team',     'チーム',             'noun', 2, 'soccer',  'Our team won the match.',            '私たちのチームが試合に勝ちました。'),
  ('captain',  'キャプテン',         'noun', 2, 'soccer',  'He is the captain of the team.',     '彼はチームのキャプテンです。'),
  ('win',      '勝つ',               'verb', 2, 'soccer',  'I want to win the game.',            '試合に勝ちたいです。'),
  ('lose',     '負ける',             'verb', 2, 'soccer',  'We don''t want to lose again.',      'もう負けたくない。'),
  ('game',     '試合・ゲーム',       'noun', 2, 'soccer',  'The game starts at three.',          '試合は3時に始まります。'),
  ('match',    '試合',               'noun', 2, 'soccer',  'We had a great match yesterday.',    '昨日素晴らしい試合をしました。'),
  ('kick',     '蹴る',               'verb', 2, 'soccer',  'He kicked the ball hard.',           '彼は強くボールを蹴りました。'),
  ('pass',     'パスする・通る',     'verb', 2, 'soccer',  'Pass me the ball, please.',          'ボールをパスして。'),
  -- L2 (continued) — feelings
  ('sad',      '悲しい',             'adj',  2, 'general', 'She was sad about the news.',        '彼女はそのニュースを聞いて悲しかったです。'),
  ('angry',    '怒った',             'adj',  2, 'general', 'Don''t be angry with me.',           '私に怒らないで。'),
  ('excited',  'わくわくした',       'adj',  2, 'general', 'I''m excited about the trip.',       '旅行が楽しみです。'),
  ('nervous',  '緊張した',           'adj',  2, 'general', 'I get nervous before tests.',        'テスト前は緊張します。'),
  ('proud',    '誇りに思う',         'adj',  2, 'general', 'I am proud of you.',                 'あなたを誇りに思います。'),
  ('glad',     'うれしい',           'adj',  2, 'general', 'I''m glad to hear that.',            'それを聞いてうれしいです。'),
  ('lonely',   'さびしい',           'adj',  2, 'general', 'He felt lonely without his family.', '家族がいなくて彼はさびしかった。'),
  ('surprised','驚いた',             'adj',  2, 'general', 'She was surprised by the gift.',     '彼女はプレゼントに驚きました。'),
  -- L2 (continued) — people
  ('parent',   '親',                 'noun', 2, 'family',  'Her parents are very kind.',         '彼女の両親はとても優しいです。'),
  ('child',    '子供',               'noun', 2, 'family',  'She has one child.',                 '彼女には子供が一人います。'),
  ('neighbor', '近所の人',           'noun', 2, 'family',  'Our new neighbor is nice.',          '新しい近所の人は親切です。'),
  ('group',    'グループ',           'noun', 2, 'general', 'We work in a small group.',          '私たちは小さなグループで作業します。'),
  -- L2 (continued) — common verbs
  ('visit',    '訪れる',             'verb', 2, 'general', 'I want to visit Kyoto.',             '京都を訪れたいです。'),
  ('travel',   '旅行する',           'verb', 2, 'general', 'She likes to travel abroad.',        '彼女は海外を旅行するのが好きです。'),
  ('arrive',   '到着する',           'verb', 2, 'general', 'The train arrives at noon.',         '電車は正午に到着します。'),
  ('leave',    '去る・出発する',     'verb', 2, 'general', 'I have to leave now.',               'もう行かなくてはなりません。'),
  ('wait',     '待つ',               'verb', 2, 'general', 'Please wait a moment.',              '少々お待ちください。'),
  ('choose',   '選ぶ',               'verb', 2, 'general', 'Choose your favorite color.',        '好きな色を選んでください。'),
  ('try',      '試す・やってみる',   'verb', 2, 'general', 'Try this new dish.',                 'この新しい料理を試してみて。'),
  ('change',   '変わる・変える',     'verb', 2, 'general', 'I want to change my plan.',          '計画を変えたいです。'),
  ('help',     '手伝う',             'verb', 2, 'general', 'Can you help me?',                   '手伝ってくれますか？'),
  ('hope',     '望む',               'verb', 2, 'general', 'I hope you feel better soon.',       '早く良くなることを願っています。'),
  ('send',     '送る',               'verb', 2, 'general', 'I will send you a message.',         'メッセージを送ります。'),
  ('share',    '共有する・分け合う', 'verb', 2, 'general', 'Let''s share this pizza.',           'このピザを分けよう。'),
  -- L2 (continued) — adjectives
  ('nice',     'すてきな',           'adj',  2, 'general', 'What a nice day!',                   'なんてすてきな日！'),
  ('kind',     '親切な',             'adj',  2, 'general', 'She is very kind to everyone.',      '彼女はみんなに親切です。'),
  ('smart',    '賢い',               'adj',  2, 'general', 'He is a smart student.',             '彼は賢い生徒です。'),
  ('fun',      '楽しい',             'adj',  2, 'general', 'The party was fun.',                 'パーティーは楽しかったです。'),
  ('interesting','興味深い',         'adj',  2, 'general', 'This book is very interesting.',     'この本はとても興味深いです。'),
  ('strong',   '強い',               'adj',  2, 'general', 'He is very strong.',                 '彼はとても強いです。'),
  ('healthy',  '健康な',             'adj',  2, 'general', 'Eating well keeps you healthy.',     'よく食べることで健康でいられます。'),
  ('beautiful','美しい',             'adj',  2, 'general', 'What a beautiful sunset.',           'なんて美しい夕焼けでしょう。'),
  -- L2 (continued) — time
  ('minute',   '分',                 'noun', 2, 'general', 'Wait one minute, please.',           '1分待ってください。'),
  ('hour',     '時間',               'noun', 2, 'general', 'I studied for two hours.',           '私は2時間勉強しました。'),

  -- ----- L3 (middle school complete, Eiken 3/Pre-2) -----
  ('between',    '〜の間に',         'prep', 3, 'general', 'Choose between tea and coffee.',     'お茶かコーヒーかの間で選んでください。'),
  ('decide',     '決める',           'verb', 3, 'general', 'I decided to study harder.',         '私はもっと勉強することに決めました。'),
  ('experience', '経験',             'noun', 3, 'general', 'It was a great experience.',         'それは素晴らしい経験でした。'),
  ('instead',    '代わりに',         'adv',  3, 'general', 'Let''s go to the park instead.',     '代わりに公園に行きましょう。'),
  ('recently',   '最近',             'adv',  3, 'general', 'I have been busy recently.',         '最近忙しいです。'),
  ('opportunity','機会',             'noun', 3, 'general', 'This is a great opportunity.',       'これは素晴らしい機会です。'),
  ('improve',    '改善する',         'verb', 3, 'general', 'I want to improve my English.',      '私は英語を上達させたいです。'),

  -- ----- L4 (high school standard, Eiken 2) -----
  ('although',   '〜だけれども',     'conj', 4, 'general', 'Although it rained, we went out.',   '雨が降ったけれども、私たちは出かけました。'),
  ('acquire',    '習得する・取得する','verb',4, 'general', 'She acquired new skills quickly.',   '彼女は新しい技能を素早く習得しました。'),
  ('sufficient', '十分な',           'adj',  4, 'general', 'We have sufficient time to prepare.','準備するための十分な時間があります。'),
  ('contribute', '貢献する',         'verb', 4, 'general', 'He contributed to the team''s win.', '彼はチームの勝利に貢献しました。'),
  ('ensure',     '確実にする',       'verb', 4, 'general', 'Please ensure the door is locked.',  'ドアが施錠されていることを確認してください。'),

  -- ----- L5 (advanced, Eiken Pre-1) -----
  ('perspective','視点',             'noun', 5, 'general', 'Try looking from a new perspective.','新しい視点で見てみてください。'),
  ('substantial','相当な',           'adj',  5, 'general', 'There was a substantial improvement.','相当な改善がありました。'),
  ('deteriorate','悪化する',         'verb', 5, 'general', 'His health began to deteriorate.',   '彼の健康は悪化し始めました。')
on conflict do nothing;
