-- ============================================================================
-- Seed: 30 sample vocabulary items spanning L1..L5
--
-- This is the smallest viable set to drive a working "today's 20" demo.
-- Categories used: daily, school, soccer, general.
-- audio_url is left null for now; we'll backfill once we record native MP3s
-- and upload them to Supabase Storage at bucket "vocab-audio".
--
-- Idempotent: re-running this file will not create duplicates because of
-- the unique index on lower(word_en).
-- ============================================================================

insert into vocabulary_items (word_en, meaning_ja, pos, level, category, example_en, example_ja) values
  -- ----- L1 (super basic, Eiken 5/4) -----
  ('water',    '水',                 'noun', 1, 'daily',  'I drink water every day.',          '私は毎日水を飲みます。'),
  ('food',     '食べ物',             'noun', 1, 'daily',  'I like Japanese food.',             '私は日本食が好きです。'),
  ('friend',   '友達',               'noun', 1, 'daily',  'She is my best friend.',            '彼女は私の親友です。'),
  ('school',   '学校',               'noun', 1, 'school', 'I go to school by bus.',            '私はバスで学校へ行きます。'),
  ('happy',    '幸せな',             'adj',  1, 'daily',  'I am happy today.',                 '私は今日幸せです。'),
  ('run',      '走る',               'verb', 1, 'daily',  'I run every morning.',              '私は毎朝走ります。'),
  ('ball',     'ボール',             'noun', 1, 'soccer', 'Pass the ball, please!',            'ボールをパスして！'),
  ('mother',   '母',                 'noun', 1, 'family', 'My mother is very kind.',           '私の母はとても優しいです。'),
  ('father',   '父',                 'noun', 1, 'family', 'My father works at a restaurant.',  '私の父はレストランで働いています。'),
  ('brother',  '兄弟',               'noun', 1, 'family', 'I have one brother.',               '私には兄弟が一人います。'),
  ('sister',   '姉妹',               'noun', 1, 'family', 'She is my older sister.',           '彼女は私の姉です。'),
  ('dog',      '犬',                 'noun', 1, 'daily',  'We have a small dog.',              '私たちは小さな犬を飼っています。'),
  ('cat',      '猫',                 'noun', 1, 'daily',  'The cat is on the chair.',          '猫がいすの上にいます。'),
  ('eat',      '食べる',             'verb', 1, 'daily',  'I eat breakfast at seven.',         '私は7時に朝食を食べます。'),
  ('drink',    '飲む',               'verb', 1, 'daily',  'Drink some water, please.',         '水を少し飲んでください。'),
  ('sleep',   '寝る',                'verb', 1, 'daily',  'I sleep eight hours a night.',      '私は一晩に8時間寝ます。'),
  ('read',    '読む',                'verb', 1, 'school', 'I read books every day.',           '私は毎日本を読みます。'),
  ('write',   '書く',                'verb', 1, 'school', 'Please write your name here.',      'ここに名前を書いてください。'),
  ('like',    '好きである',          'verb', 1, 'daily',  'I like cats very much.',            '私は猫がとても好きです。'),
  ('book',    '本',                  'noun', 1, 'school', 'This book is interesting.',         'この本は面白いです。'),
  ('pen',     'ペン',                'noun', 1, 'school', 'Can I borrow your pen?',            'あなたのペンを借りてもいいですか？'),
  ('house',   '家',                  'noun', 1, 'daily',  'Their house is very big.',          '彼らの家はとても大きいです。'),
  ('big',     '大きい',              'adj',  1, 'general','That is a big tree.',               'あれは大きな木です。'),
  ('small',   '小さい',              'adj',  1, 'general','She has a small bag.',              '彼女は小さなかばんを持っています。'),
  ('good',    'よい',                'adj',  1, 'general','Good morning, everyone!',           'みなさん、おはようございます！'),
  -- L1 (continued) — numbers
  ('one',     '1・ひとつ',           'num',  1, 'general','I have one brother.',               '兄が一人います。'),
  ('two',     '2・ふたつ',           'num',  1, 'general','I see two cats.',                   '猫が2匹見えます。'),
  ('three',   '3・みっつ',           'num',  1, 'general','I read three books.',               '本を3冊読みました。'),
  ('four',    '4・よっつ',           'num',  1, 'general','We have four apples.',              'りんごが4つあります。'),
  ('five',    '5・いつつ',           'num',  1, 'general','I have five pencils.',              '鉛筆が5本あります。'),
  -- L1 (continued) — time
  ('today',   '今日',                'noun', 1, 'daily',  'It''s sunny today.',                '今日は晴れです。'),
  ('morning', '朝',                  'noun', 1, 'daily',  'Good morning!',                     'おはよう！'),
  ('night',   '夜',                  'noun', 1, 'daily',  'Good night, everyone.',             'みなさん、おやすみなさい。'),
  ('day',     '日',                  'noun', 1, 'daily',  'Have a good day!',                  'よい一日を！'),
  -- L1 (continued) — colors
  ('red',     '赤',                  'adj',  1, 'general','I like the red one.',               '赤いのが好きです。'),
  ('blue',    '青',                  'adj',  1, 'general','The sky is blue.',                  '空は青いです。'),
  ('white',   '白',                  'adj',  1, 'general','She has a white dog.',              '彼女は白い犬を飼っています。'),
  ('black',   '黒',                  'adj',  1, 'general','He wears a black hat.',             '彼は黒い帽子をかぶっています。'),
  -- L1 (continued) — body
  ('hand',    '手',                  'noun', 1, 'general','Wash your hands.',                  '手を洗ってください。'),
  ('foot',    '足',                  'noun', 1, 'general','My foot hurts.',                    '足が痛いです。'),
  ('eye',     '目',                  'noun', 1, 'general','Close your eyes.',                  '目を閉じて。'),
  ('head',    '頭',                  'noun', 1, 'general','My head hurts.',                    '頭が痛いです。'),
  -- L1 (continued) — common verbs
  ('see',     '見る',                'verb', 1, 'daily',  'I can see the sea.',                '海が見えます。'),
  ('go',      '行く',                'verb', 1, 'daily',  'Let''s go home.',                   '家に帰ろう。'),
  ('come',    '来る',                'verb', 1, 'daily',  'Please come here.',                 'こっちに来てください。'),
  ('walk',    '歩く',                'verb', 1, 'daily',  'I walk to school.',                 '私は歩いて学校へ行きます。'),
  -- L1 (continued) — common nouns
  ('car',     '車',                  'noun', 1, 'daily',  'My father drives a car.',           '父は車を運転します。'),
  ('apple',   'りんご',              'noun', 1, 'daily',  'I eat an apple every day.',         '私は毎日りんごを食べます。'),
  ('fish',    '魚',                  'noun', 1, 'daily',  'Fish swim in the sea.',             '魚は海で泳ぎます。'),
  ('tree',    '木',                  'noun', 1, 'general','There is a big tree.',              '大きな木があります。'),
  -- L1 (continued) — numbers 6-10
  ('six',     '6・むっつ',           'num',  1, 'general','I have six fish.',                  '魚を6匹飼っています。'),
  ('seven',   '7・ななつ',           'num',  1, 'general','I get up at seven.',                '私は7時に起きます。'),
  ('eight',   '8・やっつ',           'num',  1, 'general','He sleeps for eight hours.',        '彼は8時間寝ます。'),
  ('nine',    '9・ここのつ',         'num',  1, 'general','I am nine years old.',              '私は9歳です。'),
  ('ten',     '10・とお',            'num',  1, 'general','There are ten students.',           '生徒は10人います。'),
  -- L1 (continued) — animals
  ('bird',    '鳥',                  'noun', 1, 'daily',  'A bird is flying in the sky.',      '鳥が空を飛んでいます。'),
  ('horse',   '馬',                  'noun', 1, 'daily',  'The horse runs fast.',              '馬は速く走ります。'),
  ('cow',     '牛',                  'noun', 1, 'daily',  'Cows give us milk.',                '牛は私たちにミルクをくれます。'),
  ('pig',     '豚',                  'noun', 1, 'daily',  'Our pig is very cute.',             'うちの豚はとてもかわいいです。'),
  -- L1 (continued) — body
  ('nose',    '鼻',                  'noun', 1, 'general','She has a small nose.',             '彼女は小さな鼻をしています。'),
  ('mouth',   '口',                  'noun', 1, 'general','Open your mouth.',                  '口を開けて。'),
  ('ear',     '耳',                  'noun', 1, 'general','Rabbits have long ears.',           'うさぎは長い耳を持っています。'),
  ('leg',     '脚',                  'noun', 1, 'general','My legs are tired.',                '脚が疲れました。'),
  ('arm',     '腕',                  'noun', 1, 'general','He hurt his arm.',                  '彼は腕をけがしました。'),
  -- L1 (continued) — food/drink
  ('milk',    '牛乳',                'noun', 1, 'daily',  'I drink milk every morning.',       '私は毎朝牛乳を飲みます。'),
  ('cake',    'ケーキ',              'noun', 1, 'daily',  'This cake is sweet.',               'このケーキは甘いです。'),
  ('egg',     '卵',                  'noun', 1, 'daily',  'I want two eggs, please.',          '卵を2つください。'),
  ('banana',  'バナナ',              'noun', 1, 'daily',  'Bananas are yellow.',               'バナナは黄色いです。'),
  ('tea',     'お茶',                'noun', 1, 'daily',  'Would you like some tea?',          'お茶はいかがですか？'),
  -- L1 (continued) — common verbs
  ('stop',    '止まる・止める',      'verb', 1, 'daily',  'Please stop here.',                 'ここで止まってください。'),
  ('sit',     '座る',                'verb', 1, 'daily',  'Please sit down.',                  '座ってください。'),
  ('stand',   '立つ',                'verb', 1, 'daily',  'Stand up, please.',                 '立ってください。'),
  ('open',    '開ける',              'verb', 1, 'daily',  'Open the door, please.',            'ドアを開けてください。'),
  ('close',   '閉める',              'verb', 1, 'daily',  'Close your books.',                 '本を閉じてください。'),
  ('make',    '作る',                'verb', 1, 'daily',  'Let''s make dinner together.',      '一緒に夕食を作ろう。'),
  ('give',    '与える',              'verb', 1, 'daily',  'Please give me the salt.',          '塩を取ってください。'),
  ('take',    '取る・持っていく',    'verb', 1, 'daily',  'Take this umbrella.',               'この傘を持っていってください。'),
  -- L1 (continued) — adjectives
  ('hot',     '熱い・暑い',          'adj',  1, 'general','The soup is hot.',                  'スープは熱いです。'),
  ('cold',    '冷たい・寒い',        'adj',  1, 'general','It''s cold today.',                 '今日は寒いです。'),
  ('long',    '長い',                'adj',  1, 'general','She has long hair.',                '彼女は長い髪をしています。'),
  ('fast',    '速い',                'adj',  1, 'general','He runs fast.',                     '彼は速く走ります。'),
  ('slow',    '遅い',                'adj',  1, 'general','The bus is slow today.',            '今日のバスは遅いです。'),
  -- L1 (continued) — common nouns
  ('door',    'ドア',                'noun', 1, 'daily',  'Please close the door.',            'ドアを閉めてください。'),
  ('window',  '窓',                  'noun', 1, 'daily',  'Open the window.',                  '窓を開けて。'),
  ('kitchen', '台所',                'noun', 1, 'daily',  'Mom is in the kitchen.',            '母は台所にいます。'),
  ('room',    '部屋',                'noun', 1, 'daily',  'My room is small.',                 '私の部屋は小さいです。'),
  ('park',    '公園',                'noun', 1, 'daily',  'Let''s go to the park.',            '公園に行こう。'),
  ('road',    '道',                  'noun', 1, 'general','This is a long road.',              'これは長い道です。'),
  ('street',  '通り',                'noun', 1, 'general','Don''t play in the street.',        '通りで遊ばないで。'),
  ('city',    '都市',                'noun', 1, 'general','Tokyo is a big city.',              '東京は大きな都市です。'),
  -- L1 (continued) — weather
  ('sun',     '太陽',                'noun', 1, 'general','The sun is bright.',                '太陽は明るいです。'),
  ('rain',    '雨',                  'noun', 1, 'general','It''s going to rain.',              '雨が降りそうです。'),
  ('snow',    '雪',                  'noun', 1, 'general','Snow is white.',                    '雪は白いです。'),
  ('wind',    '風',                  'noun', 1, 'general','The wind is strong today.',         '今日は風が強いです。'),
  -- L1 (continued) — family/people
  ('family',  '家族',                'noun', 1, 'family', 'I love my family.',                 '私は家族を愛しています。'),
  ('baby',    '赤ちゃん',            'noun', 1, 'family', 'The baby is sleeping.',             '赤ちゃんは寝ています。'),
  ('girl',    '女の子',              'noun', 1, 'general','She is a kind girl.',               '彼女は親切な女の子です。'),
  ('boy',     '男の子',              'noun', 1, 'general','The boy is reading a book.',        'その男の子は本を読んでいます。'),
  -- L1 (continued) — time
  ('week',    '週',                  'noun', 1, 'general','I have school five days a week.',   '私は週5日学校があります。'),
  ('year',    '年',                  'noun', 1, 'general','Happy New Year!',                   '新年おめでとう！'),

  -- ----- L2 (middle school basic, Eiken 4/3) -----
  ('play',     '(スポーツを)する・遊ぶ', 'verb', 2, 'soccer',  'I play soccer with my friends.',     '私は友達とサッカーをします。'),
  ('enjoy',    '楽しむ',             'verb', 2, 'daily',   'I enjoy reading books.',             '私は読書を楽しみます。'),
  ('practice', '練習する',           'verb', 2, 'soccer',  'We practice every day after school.','私たちは放課後毎日練習します。'),
  ('become',   '〜になる',            'verb', 2, 'general', 'I want to become a teacher.',        '私は先生になりたいです。'),
  ('important','重要な',             'adj',  2, 'general', 'It is important to study every day.','毎日勉強することは大切です。'),
  ('usually',  'たいてい',           'adv',  2, 'general', 'I usually wake up at seven.',        '私はたいてい7時に起きます。'),
  ('different','違った',             'adj',  2, 'general', 'We have different opinions.',        '私たちは違う意見を持っています。'),
  ('enough',   '十分な',             'adj',  2, 'general', 'I have enough money for lunch.',     'お昼ご飯のための十分なお金があります。'),
  ('study',    '勉強する',           'verb', 2, 'school',  'I study English every day.',         '私は毎日英語を勉強します。'),
  ('teacher',  '先生',               'noun', 2, 'school',  'My English teacher is from Canada.', '私の英語の先生はカナダ出身です。'),
  ('student',  '生徒',               'noun', 2, 'school',  'She is a high school student.',      '彼女は高校生です。'),
  ('homework', '宿題',               'noun', 2, 'school',  'I have a lot of homework today.',    '今日は宿題がたくさんあります。'),
  ('learn',    '学ぶ',               'verb', 2, 'school',  'I want to learn how to cook.',       '料理の仕方を学びたいです。'),
  ('understand','理解する',          'verb', 2, 'school',  'Do you understand this question?',   'この質問が分かりますか？'),
  ('remember', '覚えている',         'verb', 2, 'general', 'I remember her name.',               '彼女の名前を覚えています。'),
  ('forget',   '忘れる',             'verb', 2, 'general', 'Don''t forget your umbrella.',       '傘を忘れないでね。'),
  ('start',    '始める',             'verb', 2, 'daily',   'Let''s start the meeting.',          '会議を始めましょう。'),
  ('finish',   '終える',             'verb', 2, 'daily',   'I finished my report.',              'レポートを終わらせました。'),
  ('easy',     '簡単な',             'adj',  2, 'general', 'This question is easy.',             'この問題は簡単です。'),
  ('difficult','難しい',             'adj',  2, 'general', 'Math is difficult for me.',          '数学は私には難しいです。'),
  ('busy',     '忙しい',             'adj',  2, 'daily',   'She is very busy this week.',        '彼女は今週とても忙しいです。'),
  ('tired',    '疲れた',             'adj',  2, 'daily',   'I''m tired after the practice.',     '練習の後、疲れています。'),
  ('goal',     '目標・ゴール',       'noun', 2, 'soccer',  'He scored a goal in the game.',      '彼は試合でゴールを決めました。'),
  ('coach',    'コーチ',             'noun', 2, 'soccer',  'Our coach is very strict.',          '私たちのコーチはとても厳しいです。'),
  ('country',  '国',                 'noun', 2, 'daily',   'Japan is a beautiful country.',      '日本は美しい国です。'),
  -- L2 (continued) — school
  ('class',    '授業',               'noun', 2, 'school',  'We have English class at ten.',      '私たちは10時に英語の授業があります。'),
  ('library',  '図書館',             'noun', 2, 'school',  'She studies at the library.',        '彼女は図書館で勉強します。'),
  ('science',  '理科・科学',         'noun', 2, 'school',  'Science is my favorite subject.',    '理科は私の好きな科目です。'),
  ('math',     '数学',               'noun', 2, 'school',  'I have a math test tomorrow.',       '明日数学のテストがあります。'),
  ('history',  '歴史',               'noun', 2, 'school',  'I love Japanese history.',           '私は日本の歴史が大好きです。'),
  ('music',    '音楽',               'noun', 2, 'school',  'He listens to music every day.',     '彼は毎日音楽を聞きます。'),
  ('art',      '美術',               'noun', 2, 'school',  'Her art is amazing.',                '彼女のアートは素晴らしいです。'),
  ('test',     'テスト',             'noun', 2, 'school',  'I passed the test.',                 '私はテストに合格しました。'),
  ('answer',   '答え',               'noun', 2, 'school',  'What is the answer to this question?', 'この質問の答えは何ですか？'),
  ('question', '質問',               'noun', 2, 'school',  'I have a question for you.',         'あなたに質問があります。'),
  ('classroom','教室',               'noun', 2, 'school',  'The classroom is very quiet.',       '教室はとても静かです。'),
  ('lesson',   'レッスン・授業',     'noun', 2, 'school',  'Today''s lesson was interesting.',   '今日の授業は面白かったです。'),
  ('classmate','クラスメイト',       'noun', 2, 'school',  'He is my best classmate.',           '彼は私のいちばんのクラスメイトです。'),
  -- L2 (continued) — daily / travel
  ('airport',  '空港',               'noun', 2, 'daily',   'Pick me up at the airport, please.', '空港まで迎えに来てください。'),
  ('train',    '電車',               'noun', 2, 'daily',   'I take the train to school.',        '私は電車で学校へ行きます。'),
  ('station',  '駅',                 'noun', 2, 'daily',   'The station is near my house.',      '駅は私の家の近くです。'),
  ('bus',      'バス',               'noun', 2, 'daily',   'The bus comes every ten minutes.',   'バスは10分おきに来ます。'),
  ('ticket',   '切符・チケット',     'noun', 2, 'daily',   'I bought two tickets for the game.', '試合のチケットを2枚買いました。'),
  ('hotel',    'ホテル',             'noun', 2, 'daily',   'We stayed at a small hotel.',        '私たちは小さなホテルに泊まりました。'),
  ('restaurant','レストラン',        'noun', 2, 'daily',   'This restaurant is famous for sushi.', 'このレストランは寿司で有名です。'),
  ('menu',     'メニュー',           'noun', 2, 'daily',   'Can I see the menu, please?',        'メニューを見せてもらえますか？'),
  ('supermarket','スーパー',         'noun', 2, 'daily',   'I went to the supermarket after school.', '放課後スーパーへ行きました。'),
  ('weather',  '天気',               'noun', 2, 'daily',   'How is the weather today?',          '今日の天気はどうですか？'),
  ('season',   '季節',               'noun', 2, 'daily',   'Spring is my favorite season.',      '春は私の好きな季節です。'),
  ('weekend',  '週末',               'noun', 2, 'daily',   'Have a great weekend!',              'よい週末を！'),
  -- L2 (continued) — food & drink
  ('breakfast','朝食',               'noun', 2, 'daily',   'I always eat breakfast.',            '私はいつも朝食を食べます。'),
  ('dinner',   '夕食',               'noun', 2, 'daily',   'Dinner is ready!',                   '夕食ができました！'),
  ('fruit',    '果物',               'noun', 2, 'daily',   'I like fresh fruit.',                '私は新鮮な果物が好きです。'),
  ('vegetable','野菜',               'noun', 2, 'daily',   'Eat your vegetables.',               '野菜を食べなさい。'),
  ('meat',     '肉',                 'noun', 2, 'daily',   'He doesn''t eat meat.',              '彼は肉を食べません。'),
  ('rice',     'ご飯・米',           'noun', 2, 'daily',   'Japanese people eat rice every day.', '日本人は毎日ご飯を食べます。'),
  ('bread',    'パン',               'noun', 2, 'daily',   'I had bread for breakfast.',         '朝食にパンを食べました。'),
  ('juice',    'ジュース',           'noun', 2, 'daily',   'Would you like some juice?',         'ジュースはいかがですか？'),
  -- L2 (continued) — soccer
  ('team',     'チーム',             'noun', 2, 'soccer',  'Our team won the match.',            '私たちのチームが試合に勝ちました。'),
  ('captain',  'キャプテン',         'noun', 2, 'soccer',  'He is the captain of the team.',     '彼はチームのキャプテンです。'),
  ('win',      '勝つ',               'verb', 2, 'soccer',  'I want to win the game.',            '試合に勝ちたいです。'),
  ('lose',     '負ける',             'verb', 2, 'soccer',  'We don''t want to lose again.',      'もう負けたくない。'),
  ('game',     '試合・ゲーム',       'noun', 2, 'soccer',  'The game starts at three.',          '試合は3時に始まります。'),
  ('match',    '試合',               'noun', 2, 'soccer',  'We had a great match yesterday.',    '昨日素晴らしい試合をしました。'),
  ('kick',     '蹴る',               'verb', 2, 'soccer',  'He kicked the ball hard.',           '彼は強くボールを蹴りました。'),
  ('pass',     'パスする・通る',     'verb', 2, 'soccer',  'Pass me the ball, please.',          'ボールをパスして。'),
  -- L2 (continued) — feelings
  ('sad',      '悲しい',             'adj',  2, 'general', 'She was sad about the news.',        '彼女はそのニュースを聞いて悲しかったです。'),
  ('angry',    '怒った',             'adj',  2, 'general', 'Don''t be angry with me.',           '私に怒らないで。'),
  ('excited',  'わくわくした',       'adj',  2, 'general', 'I''m excited about the trip.',       '旅行が楽しみです。'),
  ('nervous',  '緊張した',           'adj',  2, 'general', 'I get nervous before tests.',        'テスト前は緊張します。'),
  ('proud',    '誇りに思う',         'adj',  2, 'general', 'I am proud of you.',                 'あなたを誇りに思います。'),
  ('glad',     'うれしい',           'adj',  2, 'general', 'I''m glad to hear that.',            'それを聞いてうれしいです。'),
  ('lonely',   'さびしい',           'adj',  2, 'general', 'He felt lonely without his family.', '家族がいなくて彼はさびしかった。'),
  ('surprised','驚いた',             'adj',  2, 'general', 'She was surprised by the gift.',     '彼女はプレゼントに驚きました。'),
  -- L2 (continued) — people
  ('parent',   '親',                 'noun', 2, 'family',  'Her parents are very kind.',         '彼女の両親はとても優しいです。'),
  ('child',    '子供',               'noun', 2, 'family',  'She has one child.',                 '彼女には子供が一人います。'),
  ('neighbor', '近所の人',           'noun', 2, 'family',  'Our new neighbor is nice.',          '新しい近所の人は親切です。'),
  ('group',    'グループ',           'noun', 2, 'general', 'We work in a small group.',          '私たちは小さなグループで作業します。'),
  -- L2 (continued) — common verbs
  ('visit',    '訪れる',             'verb', 2, 'general', 'I want to visit Kyoto.',             '京都を訪れたいです。'),
  ('travel',   '旅行する',           'verb', 2, 'general', 'She likes to travel abroad.',        '彼女は海外を旅行するのが好きです。'),
  ('arrive',   '到着する',           'verb', 2, 'general', 'The train arrives at noon.',         '電車は正午に到着します。'),
  ('leave',    '去る・出発する',     'verb', 2, 'general', 'I have to leave now.',               'もう行かなくてはなりません。'),
  ('wait',     '待つ',               'verb', 2, 'general', 'Please wait a moment.',              '少々お待ちください。'),
  ('choose',   '選ぶ',               'verb', 2, 'general', 'Choose your favorite color.',        '好きな色を選んでください。'),
  ('try',      '試す・やってみる',   'verb', 2, 'general', 'Try this new dish.',                 'この新しい料理を試してみて。'),
  ('change',   '変わる・変える',     'verb', 2, 'general', 'I want to change my plan.',          '計画を変えたいです。'),
  ('help',     '手伝う',             'verb', 2, 'general', 'Can you help me?',                   '手伝ってくれますか？'),
  ('hope',     '望む',               'verb', 2, 'general', 'I hope you feel better soon.',       '早く良くなることを願っています。'),
  ('send',     '送る',               'verb', 2, 'general', 'I will send you a message.',         'メッセージを送ります。'),
  ('share',    '共有する・分け合う', 'verb', 2, 'general', 'Let''s share this pizza.',           'このピザを分けよう。'),
  -- L2 (continued) — adjectives
  ('nice',     'すてきな',           'adj',  2, 'general', 'What a nice day!',                   'なんてすてきな日！'),
  ('kind',     '親切な',             'adj',  2, 'general', 'She is very kind to everyone.',      '彼女はみんなに親切です。'),
  ('smart',    '賢い',               'adj',  2, 'general', 'He is a smart student.',             '彼は賢い生徒です。'),
  ('fun',      '楽しい',             'adj',  2, 'general', 'The party was fun.',                 'パーティーは楽しかったです。'),
  ('interesting','興味深い',         'adj',  2, 'general', 'This book is very interesting.',     'この本はとても興味深いです。'),
  ('strong',   '強い',               'adj',  2, 'general', 'He is very strong.',                 '彼はとても強いです。'),
  ('healthy',  '健康な',             'adj',  2, 'general', 'Eating well keeps you healthy.',     'よく食べることで健康でいられます。'),
  ('beautiful','美しい',             'adj',  2, 'general', 'What a beautiful sunset.',           'なんて美しい夕焼けでしょう。'),
  -- L2 (continued) — time
  ('minute',   '分',                 'noun', 2, 'general', 'Wait one minute, please.',           '1分待ってください。'),
  ('hour',     '時間',               'noun', 2, 'general', 'I studied for two hours.',           '私は2時間勉強しました。'),
  -- L2 (continued) — shopping
  ('shop',     '店',                 'noun', 2, 'daily',   'Let''s go to the shop.',             'お店に行こう。'),
  ('money',    'お金',               'noun', 2, 'daily',   'I don''t have much money.',          'お金はあまりありません。'),
  ('buy',      '買う',               'verb', 2, 'daily',   'I want to buy a new bag.',           '新しいかばんを買いたいです。'),
  ('sell',     '売る',               'verb', 2, 'daily',   'They sell delicious cakes.',         'そこは美味しいケーキを売っています。'),
  ('pay',      '払う',               'verb', 2, 'daily',   'How much do I pay?',                 'いくら払いますか？'),
  ('price',    '値段',               'noun', 2, 'daily',   'The price is too high.',             '値段が高すぎます。'),
  ('expensive','高価な',             'adj',  2, 'daily',   'This watch is very expensive.',      'この時計はとても高価です。'),
  ('cheap',    '安い',               'adj',  2, 'daily',   'I bought a cheap pen.',              '安いペンを買いました。'),
  -- L2 (continued) — travel
  ('trip',     '旅行',               'noun', 2, 'daily',   'Have a nice trip!',                  '楽しい旅行を！'),
  ('plane',    '飛行機',             'noun', 2, 'daily',   'Our plane leaves at noon.',          '飛行機は正午に出発します。'),
  ('taxi',     'タクシー',           'noun', 2, 'daily',   'Let''s take a taxi.',                'タクシーに乗ろう。'),
  ('ship',     '船',                 'noun', 2, 'daily',   'The ship is in the harbor.',         '船は港にあります。'),
  ('map',      '地図',               'noun', 2, 'daily',   'Look at this map.',                  'この地図を見て。'),
  ('bridge',   '橋',                 'noun', 2, 'daily',   'Cross the bridge carefully.',        '橋を慎重に渡って。'),
  -- L2 (continued) — jobs / people
  ('doctor',   '医者',               'noun', 2, 'general', 'I want to be a doctor.',             '私は医者になりたいです。'),
  ('nurse',    '看護師',             'noun', 2, 'general', 'The nurse was very kind.',           '看護師さんはとても親切でした。'),
  ('engineer', '技術者',             'noun', 2, 'general', 'He works as an engineer.',           '彼は技術者として働いています。'),
  ('artist',   '芸術家',             'noun', 2, 'general', 'She is a famous artist.',            '彼女は有名な芸術家です。'),
  ('musician', '音楽家',             'noun', 2, 'general', 'My uncle is a musician.',            '私のおじは音楽家です。'),
  ('singer',   '歌手',               'noun', 2, 'general', 'She wants to be a singer.',          '彼女は歌手になりたいです。'),
  ('writer',   '作家',               'noun', 2, 'general', 'He is a young writer.',              '彼は若い作家です。'),
  ('actor',    '俳優',               'noun', 2, 'general', 'That actor is very popular.',        'その俳優はとても人気です。'),
  -- L2 (continued) — tech
  ('phone',    '電話',               'noun', 2, 'daily',   'Please answer the phone.',           '電話に出てください。'),
  ('computer', 'コンピューター',     'noun', 2, 'school',  'I use a computer at school.',        '学校でコンピューターを使います。'),
  ('internet', 'インターネット',     'noun', 2, 'general', 'I learn English on the internet.',   'インターネットで英語を学びます。'),
  ('message',  'メッセージ',         'noun', 2, 'daily',   'Send me a message.',                 'メッセージを送ってください。'),
  ('video',    '動画',               'noun', 2, 'daily',   'I watched a funny video.',           '面白い動画を見ました。'),
  ('photo',    '写真',               'noun', 2, 'daily',   'Take a photo, please.',              '写真を撮ってください。'),
  -- L2 (continued) — body actions
  ('cry',      '泣く',               'verb', 2, 'daily',   'Don''t cry, it''s okay.',            '泣かないで、大丈夫だよ。'),
  ('laugh',    '笑う',               'verb', 2, 'daily',   'We laughed a lot.',                  '私たちはたくさん笑いました。'),
  ('smile',    'ほほえむ',           'verb', 2, 'daily',   'She smiled at me.',                  '彼女は私にほほえみました。'),
  ('jump',     '跳ぶ',               'verb', 2, 'daily',   'He can jump very high.',             '彼はとても高く跳べます。'),
  ('dance',    '踊る',               'verb', 2, 'daily',   'Let''s dance together.',             '一緒に踊ろう。'),
  ('sing',     '歌う',               'verb', 2, 'daily',   'I love to sing.',                    '歌うのが大好きです。'),
  -- L2 (continued) — adjectives
  ('clean',    'きれいな',           'adj',  2, 'general', 'Keep your room clean.',              '部屋をきれいに保ってね。'),
  ('dirty',    '汚い',               'adj',  2, 'general', 'Don''t wear dirty shoes.',           '汚い靴を履かないで。'),
  ('dark',     '暗い',               'adj',  2, 'general', 'It''s dark outside.',                '外は暗いです。'),
  ('bright',   '明るい',             'adj',  2, 'general', 'The room is bright.',                '部屋は明るいです。'),
  ('soft',     'やわらかい',         'adj',  2, 'general', 'This pillow is soft.',               'この枕はやわらかいです。'),
  ('hard',     '硬い・難しい',       'adj',  2, 'general', 'The bread is hard.',                 'パンが硬いです。'),
  ('heavy',    '重い',               'adj',  2, 'general', 'This box is too heavy.',             'この箱は重すぎます。'),
  ('free',     '自由な・無料の',     'adj',  2, 'general', 'Are you free tomorrow?',             '明日は暇ですか？'),
  -- L2 (continued) — question words
  ('when',     'いつ',               'adv',  2, 'general', 'When does the movie start?',         '映画はいつ始まりますか？'),
  ('where',    'どこで',             'adv',  2, 'general', 'Where is the station?',              '駅はどこですか？'),
  ('why',      'なぜ',               'adv',  2, 'general', 'Why are you sad?',                   'なぜ悲しいのですか？'),
  ('how',      'どうやって',         'adv',  2, 'general', 'How do you go to school?',           'どうやって学校に行きますか？'),
  -- L2 (continued) — nature
  ('ocean',    '海・大洋',           'noun', 2, 'general', 'I love swimming in the ocean.',      '海で泳ぐのが大好きです。'),
  ('mountain', '山',                 'noun', 2, 'general', 'Mt. Fuji is a beautiful mountain.',  '富士山は美しい山です。'),
  ('river',    '川',                 'noun', 2, 'general', 'The river is wide.',                 '川は広いです。'),
  ('flower',   '花',                 'noun', 2, 'general', 'These flowers are pretty.',          'これらの花はかわいいです。'),

  -- ----- L3 (middle school complete, Eiken 3/Pre-2) -----
  ('between',    '〜の間に',         'prep', 3, 'general', 'Choose between tea and coffee.',     'お茶かコーヒーかの間で選んでください。'),
  ('decide',     '決める',           'verb', 3, 'general', 'I decided to study harder.',         '私はもっと勉強することに決めました。'),
  ('experience', '経験',             'noun', 3, 'general', 'It was a great experience.',         'それは素晴らしい経験でした。'),
  ('instead',    '代わりに',         'adv',  3, 'general', 'Let''s go to the park instead.',     '代わりに公園に行きましょう。'),
  ('recently',   '最近',             'adv',  3, 'general', 'I have been busy recently.',         '最近忙しいです。'),
  ('opportunity','機会',             'noun', 3, 'general', 'This is a great opportunity.',       'これは素晴らしい機会です。'),
  ('improve',    '改善する',         'verb', 3, 'general', 'I want to improve my English.',      '私は英語を上達させたいです。'),
  -- L3 (continued) — connectives
  ('however',    'しかしながら',     'adv',  3, 'general', 'It was raining; however, we went out.',  '雨が降っていたが、私たちは出かけました。'),
  ('therefore',  'そのため',         'adv',  3, 'general', 'He was tired; therefore, he went to bed.', '彼は疲れていたので寝ました。'),
  ('because',    'なぜなら',         'conj', 3, 'general', 'I''m happy because it''s sunny.',    '晴れているのでうれしいです。'),
  ('while',      '〜の間に',         'conj', 3, 'general', 'She read while I cooked.',           '私が料理する間、彼女は読書をしました。'),
  ('before',     '〜の前に',         'prep', 3, 'general', 'Wash your hands before lunch.',      '昼食前に手を洗ってください。'),
  ('after',      '〜の後に',         'prep', 3, 'general', 'I take a walk after dinner.',        '私は夕食後に散歩します。'),
  -- L3 (continued) — verbs
  ('continue',   '続ける',           'verb', 3, 'general', 'Please continue your work.',         '仕事を続けてください。'),
  ('prepare',    '準備する',         'verb', 3, 'general', 'I prepare lunch every morning.',     '私は毎朝昼食を準備します。'),
  ('suggest',    '提案する',         'verb', 3, 'general', 'He suggested a new idea.',           '彼は新しいアイデアを提案しました。'),
  ('introduce',  '紹介する',         'verb', 3, 'general', 'Let me introduce my friend.',        '友達を紹介させてください。'),
  ('succeed',    '成功する',         'verb', 3, 'general', 'She succeeded in the exam.',         '彼女は試験に合格しました。'),
  ('complete',   '完成させる',       'verb', 3, 'general', 'I completed the project.',           '私はプロジェクトを完成させました。'),
  ('develop',    '発達する・開発する','verb', 3, 'general', 'Children develop quickly.',          '子供は早く発達します。'),
  ('increase',   '増える・増やす',   'verb', 3, 'general', 'The price will increase.',           '価格が上がるでしょう。'),
  ('agree',      '同意する',         'verb', 3, 'general', 'I agree with your opinion.',         'あなたの意見に賛成です。'),
  -- L3 (continued) — abstract nouns
  ('knowledge',  '知識',             'noun', 3, 'general', 'Knowledge is power.',                '知識は力なり。'),
  ('ability',    '能力',             'noun', 3, 'general', 'She has the ability to lead.',       '彼女にはリーダーシップ能力があります。'),
  ('future',     '未来',             'noun', 3, 'general', 'What do you want to do in the future?', '将来何をしたいですか？'),
  ('reason',     '理由',             'noun', 3, 'general', 'Tell me the reason.',                '理由を教えてください。'),
  ('opinion',    '意見',             'noun', 3, 'general', 'What''s your opinion?',              'あなたの意見は？'),
  ('problem',    '問題',             'noun', 3, 'general', 'Do you have a problem?',             '問題がありますか？'),
  ('environment','環境',             'noun', 3, 'general', 'We must protect the environment.',   '私たちは環境を守らなければなりません。'),
  -- L3 (continued) — adjective
  ('dangerous',  '危険な',           'adj',  3, 'general', 'Driving fast is dangerous.',         '速く運転することは危険です。'),
  -- L3 (continued) — verbs
  ('imagine',    '想像する',         'verb', 3, 'general', 'Imagine you are a bird.',            '自分が鳥だと想像してみて。'),
  ('explain',    '説明する',         'verb', 3, 'general', 'Can you explain this?',              'これを説明してくれますか？'),
  ('accept',     '受け入れる',       'verb', 3, 'general', 'I accept your apology.',             '謝罪を受け入れます。'),
  ('realize',    '気づく・実現する', 'verb', 3, 'general', 'I realized my mistake.',             '自分の間違いに気づきました。'),
  ('notice',     '気づく',           'verb', 3, 'general', 'Did you notice his haircut?',        '彼の髪型に気づいた？'),
  ('mention',    '言及する',         'verb', 3, 'general', 'He mentioned your name.',            '彼はあなたの名前に言及しました。'),
  ('allow',      '許す',             'verb', 3, 'general', 'My parents allow me to stay up late.', '両親は私が夜更かしすることを許します。'),
  ('follow',     'ついていく',       'verb', 3, 'general', 'Please follow me.',                  '私についてきてください。'),
  ('lead',       '導く',             'verb', 3, 'general', 'She led the team to victory.',       '彼女はチームを勝利に導きました。'),
  ('depend',     '頼る・〜次第である','verb', 3, 'general', 'It depends on the weather.',         '天気次第です。'),
  ('focus',      '集中する',         'verb', 3, 'general', 'Please focus on your work.',         '仕事に集中してください。'),
  ('manage',     '管理する・なんとかする','verb', 3, 'general', 'He manages the company.',        '彼はその会社を経営しています。'),
  ('save',       '救う・節約する',   'verb', 3, 'general', 'Save your money.',                   'お金を貯めなさい。'),
  ('spend',      '過ごす・使う',     'verb', 3, 'general', 'I spend a lot of time reading.',     '私は読書に多くの時間を費やします。'),
  ('encourage',  '励ます',           'verb', 3, 'general', 'She encouraged me to try.',          '彼女は私に挑戦するよう励ましてくれました。'),
  ('compare',    '比べる',           'verb', 3, 'general', 'Don''t compare yourself to others.', '他人と自分を比べないで。'),
  ('believe',    '信じる',           'verb', 3, 'general', 'I believe in you.',                  'あなたを信じています。'),
  ('wonder',     '疑問に思う',       'verb', 3, 'general', 'I wonder what time it is.',          '何時か気になります。'),
  ('invent',     '発明する',         'verb', 3, 'general', 'Edison invented the light bulb.',    'エジソンは電球を発明した。'),
  ('afford',     '〜する余裕がある', 'verb', 3, 'general', 'I can''t afford a new car.',         '新車を買う余裕はありません。'),
  -- L3 (continued) — abstract nouns
  ('solution',   '解決法',           'noun', 3, 'general', 'We need a solution.',                '解決法が必要だ。'),
  ('situation',  '状況',             'noun', 3, 'general', 'The situation is difficult.',        '状況は難しい。'),
  ('importance', '重要さ',           'noun', 3, 'general', 'I understand the importance.',       '重要さを理解しています。'),
  ('decision',   '決定',             'noun', 3, 'general', 'It''s a hard decision.',             '難しい決定です。'),
  ('education',  '教育',             'noun', 3, 'school',  'Education is very important.',       '教育はとても大切です。'),
  ('information','情報',             'noun', 3, 'general', 'Where can I get more information?',  'もっと情報はどこで得られますか？'),
  ('behavior',   '行動',             'noun', 3, 'general', 'Her behavior was strange.',          '彼女の行動はおかしかった。'),
  ('character',  '性格',             'noun', 3, 'general', 'He has a kind character.',           '彼は優しい性格です。'),
  ('fact',       '事実',             'noun', 3, 'general', 'It is a well-known fact.',           'それは有名な事実です。'),
  ('truth',      '真実',             'noun', 3, 'general', 'Tell me the truth.',                 '真実を教えてください。'),
  ('mistake',    '間違い',           'noun', 3, 'general', 'Everyone makes mistakes.',           '誰でも間違いを犯します。'),
  ('success',    '成功',             'noun', 3, 'general', 'I wish you success.',                '成功を祈ります。'),
  ('failure',    '失敗',             'noun', 3, 'general', 'Don''t be afraid of failure.',       '失敗を恐れないで。'),
  ('society',    '社会',             'noun', 3, 'general', 'We live in a busy society.',         '私たちは忙しい社会に住んでいます。'),
  ('culture',    '文化',             'noun', 3, 'general', 'Japanese culture is rich.',          '日本の文化は豊かです。'),
  -- L3 (continued) — adjectives
  ('useful',     '役立つ',           'adj',  3, 'general', 'This tool is very useful.',          'この道具はとても役立ちます。'),
  ('possible',   '可能な',           'adj',  3, 'general', 'Anything is possible.',              '何でも可能です。'),
  ('impossible', '不可能な',         'adj',  3, 'general', 'Nothing is impossible.',             '不可能なことはない。'),
  ('popular',    '人気の',           'adj',  3, 'general', 'This song is popular.',              'この歌は人気です。'),
  ('famous',     '有名な',           'adj',  3, 'general', 'He is a famous singer.',             '彼は有名な歌手です。'),
  ('simple',     '簡単な',           'adj',  3, 'general', 'The answer is simple.',              '答えは簡単です。'),
  ('common',     '共通の・一般的な', 'adj',  3, 'general', 'It''s a common name.',               '一般的な名前です。'),
  ('perfect',    '完璧な',           'adj',  3, 'general', 'Her English is perfect.',            '彼女の英語は完璧です。'),
  ('careful',    '注意深い',         'adj',  3, 'general', 'Be careful with the knife.',         'ナイフに注意して。'),
  ('friendly',   '友好的な',         'adj',  3, 'general', 'She is very friendly.',              '彼女はとても友好的です。'),
  ('polite',     '礼儀正しい',       'adj',  3, 'general', 'He is always polite.',               '彼はいつも礼儀正しいです。'),
  ('quiet',      '静かな',           'adj',  3, 'general', 'Please be quiet.',                   '静かにしてください。'),
  ('loud',       'うるさい',         'adj',  3, 'general', 'The music is too loud.',             '音楽がうるさすぎます。'),
  ('quick',      '素早い',           'adj',  3, 'general', 'He is a quick learner.',             '彼は覚えるのが早いです。'),
  ('natural',    '自然な',           'adj',  3, 'general', 'Her smile is so natural.',           '彼女の笑顔はとても自然です。'),

  -- ----- L4 (high school standard, Eiken 2) -----
  ('although',   '〜だけれども',     'conj', 4, 'general', 'Although it rained, we went out.',   '雨が降ったけれども、私たちは出かけました。'),
  ('acquire',    '習得する・取得する','verb',4, 'general', 'She acquired new skills quickly.',   '彼女は新しい技能を素早く習得しました。'),
  ('sufficient', '十分な',           'adj',  4, 'general', 'We have sufficient time to prepare.','準備するための十分な時間があります。'),
  ('contribute', '貢献する',         'verb', 4, 'general', 'He contributed to the team''s win.', '彼はチームの勝利に貢献しました。'),
  ('ensure',     '確実にする',       'verb', 4, 'general', 'Please ensure the door is locked.',  'ドアが施錠されていることを確認してください。'),
  -- L4 (continued) — verbs
  ('discover',   '発見する',         'verb', 4, 'general', 'Scientists discovered a new planet.', '科学者たちは新しい惑星を発見した。'),
  ('examine',    '調査する',         'verb', 4, 'general', 'The doctor examined the patient.',   '医者が患者を診察した。'),
  ('consider',   '考慮する',         'verb', 4, 'general', 'Please consider my proposal.',       '私の提案を検討してください。'),
  ('demonstrate','示す・実演する',   'verb', 4, 'general', 'He demonstrated how to fix it.',     '彼は修理方法を実演した。'),
  ('estimate',   '見積もる',         'verb', 4, 'general', 'We estimate the cost at $100.',      '費用は100ドルと見積もります。'),
  ('influence',  '影響する',         'verb', 4, 'general', 'His teacher influenced him deeply.', '彼は先生に深く影響を受けた。'),
  ('maintain',   '維持する',         'verb', 4, 'general', 'We must maintain quality.',          '私たちは品質を維持しなければならない。'),
  ('publish',    '出版する',         'verb', 4, 'general', 'She published her first novel.',     '彼女は処女作を出版した。'),
  ('recognize',  '認識する',         'verb', 4, 'general', 'I didn''t recognize you.',           '君だと気づかなかった。'),
  ('require',    '必要とする',       'verb', 4, 'general', 'This job requires patience.',        'この仕事には忍耐が必要だ。'),
  -- L4 (continued) — abstract nouns
  ('concept',    '概念',             'noun', 4, 'general', 'It''s a difficult concept to grasp.', '把握しにくい概念だ。'),
  ('definition', '定義',             'noun', 4, 'general', 'What''s the definition of this word?', 'この単語の定義は何ですか？'),
  ('evidence',   '証拠',             'noun', 4, 'general', 'We need more evidence.',             'もっと証拠が必要だ。'),
  ('impact',     '影響',             'noun', 4, 'general', 'Climate change has a big impact.',   '気候変動は大きな影響を及ぼす。'),
  ('method',     '方法',             'noun', 4, 'general', 'Try a different method.',            '違う方法を試して。'),
  ('policy',     '方針',             'noun', 4, 'general', 'The company changed its policy.',    '会社は方針を変えた。'),
  -- L4 (continued) — adjectives
  ('essential',  '必要不可欠な',     'adj',  4, 'general', 'Sleep is essential for health.',     '睡眠は健康に不可欠だ。'),
  ('significant','重要な',           'adj',  4, 'general', 'There was a significant change.',    '大きな変化があった。'),
  ('obvious',    '明らかな',         'adj',  4, 'general', 'The answer is obvious.',             '答えは明らかだ。'),
  ('specific',   '特定の',           'adj',  4, 'general', 'Be more specific, please.',          'もっと具体的に言ってください。'),
  -- L4 (continued) — academic verbs
  ('analyze',    '分析する',         'verb', 4, 'general', 'We need to analyze the data.',       'データを分析する必要があります。'),
  ('claim',      '主張する',         'verb', 4, 'general', 'He claimed that he was innocent.',   '彼は無実だと主張した。'),
  ('concentrate','集中する',         'verb', 4, 'general', 'Concentrate on the task.',           '課題に集中してください。'),
  ('confirm',    '確認する',         'verb', 4, 'general', 'Please confirm your reservation.',   '予約を確認してください。'),
  ('describe',   '描写する',         'verb', 4, 'general', 'Describe what you saw.',             '見たものを描写してください。'),
  ('emphasize',  '強調する',         'verb', 4, 'general', 'She emphasized the importance.',     '彼女は重要性を強調した。'),
  ('evaluate',   '評価する',         'verb', 4, 'general', 'Teachers evaluate students.',        '先生は生徒を評価します。'),
  ('expand',     '拡大する',         'verb', 4, 'general', 'The company expanded overseas.',     '会社は海外に拡大した。'),
  ('indicate',   '示す',             'verb', 4, 'general', 'The data indicates a problem.',      'データは問題があることを示している。'),
  ('interpret',  '解釈する・通訳する','verb', 4, 'general', 'How do you interpret this poem?',    'この詩をどう解釈しますか？'),
  ('investigate','調査する',         'verb', 4, 'general', 'The police investigated the case.',  '警察は事件を調査した。'),
  ('observe',    '観察する',         'verb', 4, 'general', 'Scientists observe stars.',          '科学者は星を観察します。'),
  ('perform',    '演じる・実行する', 'verb', 4, 'general', 'The actors performed beautifully.',  '俳優たちは見事に演じた。'),
  ('preserve',   '保存する',         'verb', 4, 'general', 'We must preserve nature.',           '私たちは自然を保護しなければならない。'),
  ('respond',    '応答する',         'verb', 4, 'general', 'Please respond to my email.',        '私のメールに返信してください。'),
  ('reveal',     '明らかにする',     'verb', 4, 'general', 'The truth was revealed.',            '真実が明らかにされた。'),
  -- L4 (continued) — academic nouns
  ('authority',  '権威・当局',       'noun', 4, 'general', 'He is an authority on history.',     '彼は歴史の権威です。'),
  ('context',    '文脈',             'noun', 4, 'general', 'It depends on the context.',         '文脈によります。'),
  ('element',    '要素',             'noun', 4, 'general', 'Trust is a key element.',            '信頼は重要な要素だ。'),
  ('function',   '機能',             'noun', 4, 'general', 'What is the function of this?',      'これの機能は何ですか？'),
  ('principle',  '原則',             'noun', 4, 'general', 'Honesty is my principle.',           '正直は私の原則です。'),
  ('procedure',  '手順',             'noun', 4, 'general', 'Follow the correct procedure.',      '正しい手順に従ってください。'),
  ('structure',  '構造',             'noun', 4, 'general', 'The building has a complex structure.', 'その建物は複雑な構造を持っている。'),
  ('theory',     '理論',             'noun', 4, 'general', 'In theory, it should work.',         '理論的には、うまくいくはずだ。'),
  -- L4 (continued) — adjective
  ('complex',    '複雑な',           'adj',  4, 'general', 'This is a complex problem.',         'これは複雑な問題だ。'),

  -- ----- L5 (advanced, Eiken Pre-1) -----
  ('perspective','視点',             'noun', 5, 'general', 'Try looking from a new perspective.','新しい視点で見てみてください。'),
  ('substantial','相当な',           'adj',  5, 'general', 'There was a substantial improvement.','相当な改善がありました。'),
  ('deteriorate','悪化する',         'verb', 5, 'general', 'His health began to deteriorate.',   '彼の健康は悪化し始めました。'),
  -- L5 (continued) — sophisticated
  ('inevitable', '避けられない',     'adj',  5, 'general', 'Death is inevitable.',               '死は避けられない。'),
  ('ambiguous',  'あいまいな',       'adj',  5, 'general', 'Her answer was ambiguous.',          '彼女の答えはあいまいだった。'),
  ('profound',   '深い・重大な',     'adj',  5, 'general', 'It had a profound impact on me.',    '私に深い影響を与えた。'),
  ('articulate', '明確に表現する',   'verb', 5, 'general', 'She articulates her ideas clearly.', '彼女は考えを明確に表現する。'),
  ('eloquent',   '雄弁な',           'adj',  5, 'general', 'He gave an eloquent speech.',        '彼は雄弁なスピーチをした。'),
  ('comprehensive','包括的な',       'adj',  5, 'general', 'We need a comprehensive plan.',      '包括的な計画が必要だ。'),
  ('ubiquitous', '至るところにある', 'adj',  5, 'general', 'Smartphones are ubiquitous now.',    'スマートフォンは今や至る所にある。'),
  ('nuance',     '微妙な差・ニュアンス','noun', 5, 'general', 'Translation often loses nuance.', '翻訳ではしばしばニュアンスが失われる。'),
  ('discrepancy','不一致',           'noun', 5, 'general', 'There''s a discrepancy in the data.', 'データに不一致がある。'),
  ('paradigm',   'パラダイム・枠組み','noun', 5, 'general', 'It''s a paradigm shift.',            'パラダイムシフトだ。'),
  ('mitigate',   '軽減する',         'verb', 5, 'general', 'We must mitigate the risks.',        'リスクを軽減しなければならない。'),
  ('scrutinize', '詳しく調べる',     'verb', 5, 'general', 'He scrutinized every detail.',       '彼はあらゆる細部を詳しく調べた。'),
  -- L5 (continued) — sophisticated
  ('catalyst',     '触媒・きっかけ',           'noun', 5, 'general', 'She was the catalyst for change.',   '彼女が変化のきっかけだった。'),
  ('compelling',   '説得力のある',             'adj',  5, 'general', 'He gave a compelling argument.',     '彼は説得力のある議論を展開した。'),
  ('controversial','議論の余地のある',         'adj',  5, 'general', 'It''s a controversial decision.',    '議論を呼ぶ決定だ。'),
  ('coherent',     '一貫した',                 'adj',  5, 'general', 'Her essay was coherent.',            '彼女のエッセイは一貫していた。'),
  ('fluctuate',    '変動する',                 'verb', 5, 'general', 'Stock prices fluctuate daily.',      '株価は毎日変動する。'),
  ('hypothesis',   '仮説',                     'noun', 5, 'general', 'They tested the hypothesis.',        '彼らは仮説を検証した。'),
  ('implement',    '実行する',                 'verb', 5, 'general', 'We will implement the plan.',        '計画を実行します。'),
  ('intricate',    '複雑な・入り組んだ',       'adj',  5, 'general', 'The pattern is very intricate.',     'その模様はとても入り組んでいる。'),
  ('juxtapose',    '並置する',                 'verb', 5, 'general', 'The artist juxtaposed light and dark.', '画家は光と影を並置した。'),
  ('notwithstanding','〜にもかかわらず',       'prep', 5, 'general', 'Notwithstanding the rain, we went out.', '雨にもかかわらず、私たちは出かけた。'),
  ('pertinent',    '適切な・関連した',         'adj',  5, 'general', 'That is a pertinent question.',      'それは適切な質問です。'),
  ('quintessential','典型的な',                'adj',  5, 'general', 'He is the quintessential gentleman.','彼は典型的な紳士だ。'),
  ('resilient',    '回復力のある',             'adj',  5, 'general', 'Children are remarkably resilient.', '子供たちは驚くほど回復力がある。'),
  ('tangible',     '明白な・具体的な',         'adj',  5, 'general', 'We need tangible results.',          '具体的な成果が必要だ。'),
  ('unprecedented','前例のない',               'adj',  5, 'general', 'It''s an unprecedented event.',      '前例のない出来事だ。')
on conflict do nothing;
